# Generated by Django 5.1.2 on 2024-12-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambName', models.CharField(max_length=100)),
                ('ambPos', models.CharField(max_length=100)),
                ('ambPnumber', models.CharField(max_length=100)),
                ('ambEmail', models.CharField(max_length=100)),
                ('ambSocial', models.CharField(max_length=100)),
                ('ambDateOfHire', models.CharField(max_length=100)),
                ('ambBirthdate', models.CharField(max_length=100)),
                ('ambAdr', models.CharField(max_length=100)),
            ],
        ),
    ]
