# Generated by Django 5.1.2 on 2024-12-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambassador',
            old_name='ambAdr',
            new_name='ambAdrV',
        ),
        migrations.RenameField(
            model_name='ambassador',
            old_name='ambBirthdate',
            new_name='ambBirthdateV',
        ),
        migrations.RenameField(
            model_name='ambassador',
            old_name='ambDateOfHire',
            new_name='ambDateOfHireV',
        ),
        migrations.RenameField(
            model_name='ambassador',
            old_name='ambEmail',
            new_name='ambEmailV',
        ),
        migrations.RenameField(
            model_name='ambassador',
            old_name='ambName',
            new_name='ambNameV',
        ),
        migrations.RenameField(
            model_name='ambassador',
            old_name='ambPnumber',
            new_name='ambPnumberV',
        ),
        migrations.RenameField(
            model_name='ambassador',
            old_name='ambPos',
            new_name='ambPosV',
        ),
        migrations.RenameField(
            model_name='ambassador',
            old_name='ambSocial',
            new_name='ambSocialV',
        ),
    ]
