# Generated by Django 5.1.2 on 2024-12-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsApp', '0002_rename_ambadr_ambassador_ambadrv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='ambIdV',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
