# Generated by Django 5.1.2 on 2024-12-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsApp', '0003_ambassador_ambidv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemIdV', models.CharField(max_length=100)),
                ('itemNameV', models.CharField(max_length=100)),
                ('itemQtyV', models.CharField(max_length=100)),
                ('itemPriceV', models.CharField(max_length=100)),
                ('itemDescV', models.CharField(max_length=100)),
            ],
        ),
    ]
